all:
	# javac Puissance4.java
	# javac Puissance4ColonneException.java
	# javac ControleurPuissance4Txt.java
	# javac VuePuissance4Txt.java
	# javac ControleurVuePuissance4Graphique.java
	javac ControleurPuissance4Graphique.java
	javac Puissance4GraphiqueTxt.java
