all:
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/Dessinable.java
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/DessinablesData.java
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/Dessin.java
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/Figure.java
	
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/Utilitaires.java
	
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/Cercle.java
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/DessineCercleListener.java
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/Rectangle.java
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/DessineRectangleListener.java
	
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/Controle.java
	javac -cp ./classes/ -d classes/ src/fr/insarouen/asi/minigimp/MiniGimp.java

exe :
	java -cp ./classes/ fr.insarouen.asi.minigimp.MiniGimp
